name 'gnubila-france-nfs'
version '0.0.4'
author 'Baptiste Grenier <bgrenier@gnubila.fr>'
summary 'Simple nfs server and client configuration'
description 'This modules allows to configure nfs'
licence 'Apache'
project_page 'https://github.com/gnubila-france/puppet-nfs'
